### ISSUE TITLE
"Setup with SQLite" doesn't contain hint to set "SETUP_COMPLETED=true" in .env file

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce-Website#25]
See https://github.com/Kovah/LinkAce/issues/340

**Comment by gu1ll0me** [comment]
As stated by WalterFaber in https://github.com/Kovah/LinkAce/issues/340, this step also affects"Setup with PostgreSQL".

[This page](https://www.linkace.org/docs/v1/setup/setup-with-postgresql/) should also be updated.

Thank you.

**Comment by Kovah** [comment]
Hm, this should not be needed anymore as of version 1.10 as the setting is not relevant anymore. 🤔 Did you run into issues with Postgres setup?

**Comment by gu1ll0me** [comment]
Yes. Here is my installation steps:

1. `docker-compose up -d` with these environment variables:
    ```
    [...]
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_DATABASE: linkace
      DB_USERNAME: usern@me
      DB_PASSWORD: p@ssword
    ```
2. `docker exec linkace php artisan key:generate --show`
3. Add `APP_KEY` to environment variables and `docker-compose up -d --force-recreate`
4. `docker exec -it linkace php artisan migrate`
5. `docker exec -it linkace php artisan registeruser`

When I access the Linkace host IP, the setup page is displayed. I have to create the `.env` file and set the correct permissions to go through the steps. When I click Configure database, the process hangs and finally ends with `504 Gateway Time-out`. The log shows `ERROR: SQLSTATE[HY000] [2006] MySQL server has gone away`.

If I repeat this exact steps but with `SETUP_COMPLETED: true` in the environment variables from the beginning of the process, I see the login page and can login successfully after step 5.
